# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# =============
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UAARG
email: uaarginfo@uaarg.com
description: >- # this means to ignore newlines until "baseurl:"
   Website for the University of Alberta Aerial Robotics Group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uaarg.com" # the base hostname & protocol for your site, e.g. http://example.com

image_dir: "assets/images"

show_member_img: false

# Collections
# ===========
collections_dir: "collections"
collections:
  - members

# Build settings
# ==============
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

