inc:
  # Blog Information
  title:        "UAARG"
  subtitle:     "University of Alberta Aerial Robotics Group"
  cover_image:  2014-usc-team.jpg
  logo:         uaarg-logo.png
  
  # Company information
  company:      University of Alberta Aerial Robotics Group
  url:          uaarg.com
  # facebook:     uaarg
  # twitter:      uaarg
  # gplus:        '101183822199340201470'
  about_link:   /about
  
  # Product Information
  #product_link: http://incorporated.sendtoinc.com/
  #tagline:      ""
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname: "uaarg"
  
  # Sharing settings
  sharing:
    twitter:    false
    facebook:   true
    gplus:      false
    hn:         false
    
  
 # Analytics     
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://uaarg.com
source:      .
destination: ./_site
layouts_dir:     _layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

gems: [jekyll-paginate, jekyll-assets]

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter:    true

#relative_permalinks: true

paginate_path: 'blog/page:num'
paginate: 10

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
